CREATE OR REPLACE VIEW vw_vendas AS

SELECT
P.ID_PEDIDO AS PEDIDO,
C.NOME AS CLIENTE,
V.NOME AS VENDEDOR,
PR.NOME AS PRODUTO,
CA.NOME AS CATEGORIA,

I.QUANTIDADE AS QTD,
I.PRECO_UNITARIO AS PRECO_UNITARIO,

I.QUANTIDADE * I.PRECO_UNITARIO AS FATURAMENTO,

P.DATA_PEDIDO AS DATA_PEDIDO,

PR.CUSTO AS CUSTO_UNITARIO,
I.QUANTIDADE * PR.CUSTO AS CUSTO_TOTAL,

C.ID_CLIENTE AS ID_CLIENTE,
V.ID_VENDEDOR AS ID_VENDEDOR,
PR.ID_PRODUTO AS ID_PRODUTO,
CA.ID_CATEGORIA AS ID_CATEGORIA

FROM PEDIDO P

INNER JOIN CLIENTE C
ON P.ID_CLIENTE = C.ID_CLIENTE

INNER JOIN VENDEDOR V
ON P.ID_VENDEDOR = V.ID_VENDEDOR

INNER JOIN ITENS_PEDIDO I
ON I.ID_PEDIDO = P.ID_PEDIDO

INNER JOIN PRODUTO PR
ON I.ID_PRODUTO = PR.ID_PRODUTO

INNER JOIN CATEGORIA CA
ON PR.ID_CATEGORIA = CA.ID_CATEGORIA;


SELECT
     C.NOME AS CATEGORIA,
	 COUNT(*) AS TOTAL_PRODUTOS
FROM PRODUTO P
INNER JOIN CATEGORIA C
ON P.ID_CATEGORIA = C.ID_CATEGORIA
GROUP BY NOME
ORDER BY TOTAL_PRODUTOS DESC;

SELECT
     C.ID_CATEGORIA,
     C.NOME AS CATEGORIA,
	 COUNT(*) AS TOTAL_PRODUTOS,
	 ROUND(AVG(P.PRECO),2) AS PRECO_MEDIO
FROM PRODUTO P
INNER JOIN CATEGORIA C
ON P.ID_CATEGORIA = C.ID_CATEGORIA
GROUP BY C.ID_CATEGORIA, C.NOME
ORDER BY PRECO_MEDIO DESC;

SELECT
     C.ID_CLIENTE,
     C.NOME AS CLIENTE,
	 COUNT(P.ID_PEDIDO) AS TOTAL_PEDIDOS
FROM CLIENTE C
INNER JOIN PEDIDO P
     ON C.ID_CLIENTE = P.ID_CLIENTE
GROUP BY  
     C.ID_CLIENTE, 
     C.NOME
ORDER BY TOTAL_PEDIDOS DESC;

SELECT
     V.NOME AS VENDEDOR,
	 C.NOME AS CLIENTE,
	 COUNT(P.ID_PEDIDO) AS TOTAL_PEDIDOS
FROM PEDIDO P
INNER JOIN VENDEDOR V
     ON P.ID_VENDEDOR = V.ID_VENDEDOR
INNER JOIN CLIENTE C
     ON P.ID_CLIENTE = C.ID_CLIENTE
GROUP BY
     V.NOME,
	 C.NOME
ORDER BY TOTAL_PEDIDOS DESC;

SELECT
     P.ID_PEDIDO,
     C.NOME AS CLIENTE,
	 SUM(I.QUANTIDADE * I.PRECO_UNITARIO) AS VALOR_TOTAL_PEDIDO
FROM PEDIDO P
INNER JOIN CLIENTE C
     ON P.ID_CLIENTE = C.ID_CLIENTE
INNER JOIN ITENS_PEDIDO I
     ON P.ID_PEDIDO = I.ID_PEDIDO
GROUP BY
     P.ID_PEDIDO,
	 C.NOME
ORDER BY VALOR_TOTAL_PEDIDO DESC;

SELECT
     C.ID_CLIENTE,
	 C.NOME AS CLIENTE,
	 SUM(I.QUANTIDADE * I.PRECO_UNITARIO) AS TOTAL_GASTO
FROM CLIENTE C

INNER JOIN PEDIDO P
     ON C.ID_CLIENTE = P.ID_CLIENTE
	 
INNER JOIN ITENS_PEDIDO I
     ON P.ID_PEDIDO = I.ID_PEDIDO
	 
GROUP BY
     C.ID_CLIENTE,
	 C.NOME
	 
ORDER BY TOTAL_GASTO DESC;

SELECT
     P.ID_PRODUTO,
	 P.NOME AS PRODUTO,
	 C.NOME AS CATEGORIA,
	 SUM(I.QUANTIDADE) AS QUANTIDADE_VENDIDA,
	 SUM(I.QUANTIDADE * I.PRECO_UNITARIO) AS FATURAMENTO
FROM PRODUTO P

INNER JOIN CATEGORIA C
     ON P.ID_CATEGORIA = C.ID_CATEGORIA
	 
INNER JOIN ITENS_PEDIDO I
     ON I.ID_PRODUTO = P.ID_PRODUTO
	 
GROUP BY
     P.ID_PRODUTO,
	 P.NOME,
	 C.NOME
	 
ORDER BY FATURAMENTO DESC;

SELECT
     V.ID_VENDEDOR,
	 V.NOME AS VENDEDOR,
	 COUNT(DISTINCT P.ID_PEDIDO) AS TOTAL_PEDIDOS,
	 SUM(I.QUANTIDADE) AS ITENS_VENDIDOS,
	 SUM(I.QUANTIDADE * I.PRECO_UNITARIO) AS FATURAMENTO
FROM VENDEDOR V

INNER JOIN PEDIDO P
     ON V.ID_VENDEDOR = P.ID_VENDEDOR
	 
INNER JOIN ITENS_PEDIDO I
     ON P.ID_PEDIDO = I.ID_PEDIDO
	 
GROUP BY
     V.ID_VENDEDOR,
	 V.NOME

ORDER BY FATURAMENTO DESC;

SELECT
     P.ID_PRODUTO,
	 P.NOME AS PRODUTO,
	 SUM(I.QUANTIDADE) AS QTD_VENDIDA,
	 SUM(I.QUANTIDADE * I.PRECO_UNITARIO) AS FATURAMENTO
FROM PRODUTO P

INNER JOIN ITENS_PEDIDO I
     ON I.ID_PRODUTO = P.ID_PRODUTO
	 
GROUP BY
     P.ID_PRODUTO,
     P.NOME
	 
ORDER BY FATURAMENTO DESC;

SELECT
	 C.NOME AS CATEGORIA,
	 SUM(I.QUANTIDADE) AS QTD_VENDIDA,
	 SUM(I.QUANTIDADE * I.PRECO_UNITARIO) AS FATURAMENTO
FROM CATEGORIA C
INNER JOIN PRODUTO P
     ON P.ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN ITENS_PEDIDO I
     ON I.ID_PRODUTO = P.ID_PRODUTO
GROUP BY C.NOME
ORDER BY FATURAMENTO DESC;

SELECT
     ID_PEDIDO,
	 SUM(QUANTIDADE * PRECO_UNITARIO) AS VALOR_PEDIDO
FROM ITENS_PEDIDO
GROUP BY ID_PEDIDO
ORDER BY VALOR_PEDIDO DESC;

SELECT
     ROUND(AVG(VALOR_PEDIDO),2) AS TICKET_MEDIO
FROM(
    SELECT
     ID_PEDIDO,
	 SUM(QUANTIDADE * PRECO_UNITARIO) AS VALOR_PEDIDO
FROM ITENS_PEDIDO
GROUP BY ID_PEDIDO
) AS PEDIDOS;

SELECT
	 V.NOME AS VENDEDOR,
	 P.ID_PEDIDO,
	 SUM(I.QUANTIDADE * I.PRECO_UNITARIO) AS FATURAMENTO
FROM VENDEDOR V
INNER JOIN PEDIDO P
ON P.ID_VENDEDOR = V.ID_VENDEDOR
INNER JOIN ITENS_PEDIDO I
ON I.ID_PEDIDO = P.ID_PEDIDO
GROUP BY V.NOME, P.ID_PEDIDO
ORDER BY 3 DESC;

SELECT
     VENDEDOR,
	 COUNT(*) AS TOTAL_PEDIDOS,
     ROUND(AVG(FATURAMENTO),2) AS TICKET_MEDIO
FROM(
     SELECT
	 V.NOME AS VENDEDOR,
	 P.ID_PEDIDO,
	 SUM(I.QUANTIDADE * I.PRECO_UNITARIO) AS FATURAMENTO
FROM VENDEDOR V
INNER JOIN PEDIDO P
ON P.ID_VENDEDOR = V.ID_VENDEDOR
INNER JOIN ITENS_PEDIDO I
ON I.ID_PEDIDO = P.ID_PEDIDO
GROUP BY V.NOME, P.ID_PEDIDO
) AS PEDIDOS
GROUP BY VENDEDOR
ORDER BY TICKET_MEDIO DESC;

SELECT
     VENDEDOR,
	 COUNT(*) AS TOTAL_PEDIDOS,
	 SUM(FATURAMENTO) AS FATURAMENTO_TOTAL,
     ROUND(AVG(FATURAMENTO),2) AS TICKET_MEDIO
FROM(
     SELECT
	 V.NOME AS VENDEDOR,
	 P.ID_PEDIDO,
	 SUM(I.QUANTIDADE * I.PRECO_UNITARIO) AS FATURAMENTO
FROM VENDEDOR V
INNER JOIN PEDIDO P
ON P.ID_VENDEDOR = V.ID_VENDEDOR
INNER JOIN ITENS_PEDIDO I
ON I.ID_PEDIDO = P.ID_PEDIDO
GROUP BY V.NOME, P.ID_PEDIDO
) AS PEDIDOS
GROUP BY VENDEDOR
ORDER BY FATURAMENTO_TOTAL DESC;

SELECT
     VENDEDOR,
	 COUNT(*) AS TOTAL_PEDIDOS,
	 SUM(FATURAMENTO) AS FATURAMENTO_TOTAL,
     ROUND(AVG(FATURAMENTO),2) AS TICKET_MEDIO,
	 RANK() OVER(ORDER BY SUM(FATURAMENTO) DESC) AS RANKING 
FROM(
     SELECT
	 V.NOME AS VENDEDOR,
	 P.ID_PEDIDO,
	 SUM(I.QUANTIDADE * I.PRECO_UNITARIO) AS FATURAMENTO
FROM VENDEDOR V
INNER JOIN PEDIDO P
ON P.ID_VENDEDOR = V.ID_VENDEDOR
INNER JOIN ITENS_PEDIDO I
ON I.ID_PEDIDO = P.ID_PEDIDO
GROUP BY V.NOME, P.ID_PEDIDO
) AS PEDIDOS
GROUP BY VENDEDOR
ORDER BY FATURAMENTO_TOTAL DESC;
	 
SELECT
     P.ID_PEDIDO AS PEDIDO,
     C.NOME AS CLIENTE,
     V.NOME AS VENDEDOR,
     PR.NOME AS PRODUTO,
     CA.NOME AS CATEGORIA,
     I.QUANTIDADE AS QTD,
     I.PRECO_UNITARIO AS PRECO_UNITARIO,
     I.QUANTIDADE * I.PRECO_UNITARIO AS FATURAMENTO
FROM PEDIDO P 
INNER JOIN CLIENTE C
ON P.ID_CLIENTE = C.ID_CLIENTE
INNER JOIN VENDEDOR V
ON P.ID_VENDEDOR = V.ID_VENDEDOR
INNER JOIN ITENS_PEDIDO I
ON I.ID_PEDIDO = P.ID_PEDIDO
INNER JOIN PRODUTO PR
ON I.ID_PRODUTO = PR.ID_PRODUTO
INNER JOIN CATEGORIA CA
ON PR.ID_CATEGORIA = CA.ID_CATEGORIA;

CREATE OR REPLACE VIEW vw_vendas AS

SELECT
P.ID_PEDIDO AS PEDIDO,
C.NOME AS CLIENTE,
V.NOME AS VENDEDOR,
PR.NOME AS PRODUTO,
CA.NOME AS CATEGORIA,

I.QUANTIDADE AS QTD,
I.PRECO_UNITARIO AS PRECO_UNITARIO,

I.QUANTIDADE * I.PRECO_UNITARIO AS FATURAMENTO,

P.DATA_PEDIDO AS DATA_PEDIDO,

PR.CUSTO AS CUSTO_UNITARIO,
I.QUANTIDADE * PR.CUSTO AS CUSTO_TOTAL,

C.ID_CLIENTE AS ID_CLIENTE,
V.ID_VENDEDOR AS ID_VENDEDOR,
PR.ID_PRODUTO AS ID_PRODUTO,
CA.ID_CATEGORIA AS ID_CATEGORIA

FROM PEDIDO P

INNER JOIN CLIENTE C
ON P.ID_CLIENTE = C.ID_CLIENTE

INNER JOIN VENDEDOR V
ON P.ID_VENDEDOR = V.ID_VENDEDOR

INNER JOIN ITENS_PEDIDO I
ON I.ID_PEDIDO = P.ID_PEDIDO

INNER JOIN PRODUTO PR
ON I.ID_PRODUTO = PR.ID_PRODUTO

INNER JOIN CATEGORIA CA
ON PR.ID_CATEGORIA = CA.ID_CATEGORIA;

SELECT *
FROM vw_vendas;

SELECT
     VENDEDOR,
	 COUNT(DISTINCT PEDIDO) AS TOTAL_PEDIDOS,
	 SUM(QTD) AS ITENS_VENDIDOS,
	 SUM(FATURAMENTO) AS FATURAMENTO
FROM vw_vendas
GROUP BY VENDEDOR
ORDER BY FATURAMENTO DESC;

SELECT
     CATEGORIA,
	 COUNT(DISTINCT PEDIDO) AS TOTAL_PEDIDOS,
	 SUM(QTD) AS ITENS_VENDIDOS,
	 SUM(FATURAMENTO) AS FATURAMENTO
FROM vw_vendas
GROUP BY CATEGORIA
ORDER BY FATURAMENTO DESC;

SELECT
     PRODUTO,
	 CATEGORIA,
	 SUM(QTD) AS QTD_VENDIDA,
	 SUM(FATURAMENTO) AS FATURAMENTO
FROM vw_vendas
GROUP BY PRODUTO, CATEGORIA
ORDER BY FATURAMENTO DESC;

SELECT
     CLIENTE,
	 COUNT(DISTINCT PEDIDO) AS TOTAL_PEDIDOS,
	 SUM(QTD) AS ITENS_COMPRADOS,
	 SUM(FATURAMENTO) AS TOTAL_GASTO
FROM vw_vendas
GROUP BY CLIENTE
ORDER BY TOTAL_GASTO DESC;
